/*задание 14*/
SELECT * FROM T_SUPPLY;
SELECT * FROM T_INPRICE;

/*задание 15*/
SELECT ID_MATERIAL, NAME, ID_GROUP FROM T_MATERIAL;
    
/*задание 16*/
SELECT NAME, SURNAME, FATHER_NAME, BIRTHDATE FROM T_EMPLOYER;


/*задание 17*/
SELECT * FROM T_EMPLOYER 
  WHERE SEX = 'М';

/*задание 18*/
SELECT * FROM T_CATERER 
  WHERE ID_CATERER IN
    (SELECT ID_CATERER FROM T_SUPPLY
    WHERE SUPPLY_DATE >= '01.03.2009'
    AND SUPPLY_DATE <= '30.06.2009');

/*задание 19*/
SELECT * FROM T_SECTION
  WHERE ID_SECTION IN
  (SELECT ID_SECTION FROM T_DELIVER
  WHERE DELIVER_DATE >= '01.08.2009'
  AND DELIVER_DATE <= '31.08.2009');

/*задание 20*/
SELECT NAME FROM T_SECTION
  WHERE ID_SECTION IN
  (SELECT ID_SECTION FROM T_DELIVER
  WHERE DELIVER_DATE = SYSDATE);

/*задание 21*/
SELECT NAME FROM T_MATERIAL
  WHERE ID_MATERIAL IN
  (SELECT ID_MATERIAL FROM T_SUPPLY
  WHERE SUPPLY_DATE >= '01.01.2017'
  AND SUPPLY_DATE <= SYSDATE);

/*задание 22*/
SELECT NAME FROM T_MATERIAL
  WHERE ID_MATERIAL NOT IN
  (SELECT ID_MATERIAL FROM T_SUPPLY 
  WHERE SUPPLY_DATE >= '01.01.2017'
    AND SUPPLY_DATE <= SYSDATE)
  AND ID_MATERIAL IN
  (SELECT ID_MATERIAL FROM T_SURPLUS 
  WHERE VOLUME LIKE 0);


/*задание 23*/
SELECT T_SECTION.ID_SECTION, T_SECTION.NAME, T_EMPLOYER.SURNAME, T_EMPLOYER.NAME, T_EMPLOYER.FATHER_NAME
  FROM T_SECTION, T_EMPLOYER
  WHERE T_SECTION.ID_EMPLOYER = T_EMPLOYER.ID_EMPLOYER;

/*задание 24*/
SELECT T_SECTION.ID_SECTION, T_SECTION.NAME, T_EMPLOYER.NAME, T_EMPLOYER.SURNAME, T_EMPLOYER.FATHER_NAME, T_JOB.NAME
  FROM T_SECTION, T_EMPLOYER, T_JOB
  WHERE T_SECTION.ID_EMPLOYER = T_EMPLOYER.ID_EMPLOYER AND T_EMPLOYER.ID_JOB = T_JOB.ID_JOB;

/*задание 25*/
SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE 
  FROM T_CATERER tc, T_MATERIAL tm, T_SUPPLY ts, T_INPRICE ti 
  WHERE tc.ID_CATERER = ts.ID_CATERER AND tm.ID_MATERIAL = ts.ID_MATERIAL AND ti.ID_MATERIAL = tm.ID_MATERIAL 
  AND ts.SUPPLY_DATE BETWEEN '01.01.2009' AND '31.03.2009';

/*задание 26*/
SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE FROM T_CATERER tc, T_MATERIAL tm, T_SUPPLY ts, T_INPRICE ti 
  WHERE tc.ID_CATERER = ts.ID_CATERER AND tm.ID_MATERIAL = ts.ID_MATERIAL AND ti.ID_MATERIAL = tm.ID_MATERIAL 
  AND ts.SUPPLY_DATE BETWEEN '01.01.2009' AND '31.03.2009' AND tc.ACTUAL_ADDRESS LIKE '%Пермь%';

/*задание 27*/
SELECT tm.NAME, ts.VOLUME, ts1.NAME 
  FROM T_MATERIAL tm, T_SUPPLY ts, T_STORE ts1 
  WHERE tm.ID_MATERIAL = ts.ID_MATERIAL AND ts1.ID_STORE = ts.ID_STORE;

/*задание 28*/
SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE, ts.SUPPLY_DATE
  FROM T_CATERER tc 
  JOIN T_MATERIAL tm ON tc.ID_CATERER IN
  (SELECT ID_CATERER FROM T_SUPPLY ts WHERE SUPPLY_DATE BETWEEN '01.01.2009' AND '31.03.2009')
  JOIN T_SUPPLY ts ON ts.ID_MATERIAL = tm.ID_MATERIAL AND ts.ID_CATERER = tc.ID_CATERER
  JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL;

/*задание 29*/
SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE, ts.SUPPLY_DATE
  FROM T_CATERER tc 
  LEFT JOIN T_SUPPLY ts ON ts.ID_CATERER = tc.ID_CATERER
  LEFT JOIN T_MATERIAL tm ON ts.ID_MATERIAL = tm.ID_MATERIAL
  LEFT JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL;

/*задание 30*/
SELECT ts.ID_STORE, ts.NAME, tm.NAME, ts1.VOLUME
  FROM T_STORE ts LEFT JOIN T_SURPLUS ts1 ON ts.ID_STORE = ts1.ID_STORE
  LEFT JOIN T_MATERIAL tm ON tm.ID_MATERIAL = ts1.ID_MATERIAL;

/*задание 31*/
SELECT tm1.NAME, tm.ID_MATERIAL, tm.NAME, ti.PRICE
  FROM T_MATERIAL tm JOIN T_MEASURE tm1 ON tm.ID_MEASURE = tm1.ID_MEASURE
  JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL AND ti.PRICE_DATE IN
    (SELECT PRICE_DATE FROM T_INPRICE 
       WHERE PRICE_DATE BETWEEN '01.07.2009' AND '30.09.2009');

/*задание 32*/
SELECT tm1.NAME, tm.ID_MATERIAL, tm.NAME, ti.PRICE
  FROM T_MATERIAL tm LEFT JOIN T_MEASURE tm1 ON tm.ID_MEASURE = tm1.ID_MEASURE
  LEFT JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL;

/*задание 33*/
ALTER TABLE T_EMPLOYER
  ADD id_manager INT;
UPDATE T_EMPLOYER
  SET ID_MANAGER = 1
    WHERE ID_EMPLOYER BETWEEN 2 AND 4;
UPDATE T_EMPLOYER
  SET ID_MANAGER = 5
    WHERE ID_EMPLOYER LIKE 1;

/*задание 34*/
ALTER TABLE T_GROUP
  ADD NEW_GROUP INT;
UPDATE T_GROUP
  SET NEW_GROUP = 1
    WHERE ID_GROUP BETWEEN 1 AND 5;
UPDATE T_GROUP
  SET MINI_GROUP = 2
    WHERE ID_GROUP < 3;
UPDATE T_GROUP
  SET MINI_GROUP = 3
    WHERE ID_GROUP > 3;

/*задание 35*/
CREATE TABLE T_Exemp (
  ID_EMPLOYER INT NOT NULL,
  SURNAME VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  FATHER_NAME VARCHAR2(30) NOT NULL,
  SEX CHAR,
  BIRTHDATE DATE,
  ID_MANAGER INT,
  ID_JOB INT,
  CONSTRAINT pk_exemp PRIMARY KEY (ID_EMPLOYER)
  );
INSERT INTO T_EXEMP (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME, BIRTHDATE, ID_MANAGER, ID_JOB)
  VALUES (seq_employer.NEXTVAL, 'Шилова', 'Анна', 'Ильинична', '17.07.1996', 1, 1);
INSERT INTO T_EXEMP (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME, BIRTHDATE, ID_MANAGER, ID_JOB)
  VALUES (seq_employer.NEXTVAL, 'Рылова', 'Виктория', 'Александровна', '07.05.1990', 1, 3);
INSERT INTO T_EXEMP (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME, BIRTHDATE, ID_MANAGER, ID_JOB)
  VALUES (seq_employer.NEXTVAL, 'Иванова', 'Анастасия', 'Викторовна', '05.05.1985', 2, 3);

/*задание 36*/
ALTER TABLE T_EXEMP
  ADD DISMISSED DATE;
UPDATE T_EXEMP
  SET DISMISSED = '12.03.2009';

/*задание 37*/
CREATE TABLE T_Contact (
  ID_CONTACT INT NOT NULL,
  ID_CATERER INT,
  SURNAME NVARCHAR2(20) NOT NULL,
  NAME NVARCHAR2(20) NOT NULL,
  FATHER_NAME NVARCHAR2(30),
  PHONE NUMBER(11) NOT NULL,
  CONSTRAINT PK_Contact PRIMARY KEY (ID_CONTACT),
  CONSTRAINT FK_Contact_Caterer
    FOREIGN KEY (ID_CATERER) REFERENCES T_CATERER(ID_CATERER) ON DELETE CASCADE
);
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, SURNAME, NAME, FATHER_NAME, PHONE)
  VALUES (1, 1, 'Быков', 'Альберт', 'Константинович', '89124567898');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, SURNAME, NAME, FATHER_NAME, PHONE)
  VALUES (2, 2, 'Волков', 'Андрей', 'Евгеньевич', '89508612374');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, SURNAME, NAME, FATHER_NAME, PHONE)
  VALUES (3, 3, 'Андреев', 'Глеб', 'Викторович', '89384973215');

/*задание 38*/
SELECT * FROM T_CATERER
  ORDER BY NAME;

/*задание 39*/
SELECT * FROM T_CATERER tc JOIN T_CONTACT tc1
  ON tc.ID_CATERER = tc1.ID_CATERER
  ORDER BY tc.NAME, tc1.SURNAME, tc1.NAME, tc1.FATHER_NAME;

/*задание 40*/
SELECT ts.NAME, tm.NAME, ts1.VOLUME
  FROM T_STORE ts LEFT JOIN T_SURPLUS ts1  ON ts.ID_STORE = ts1.ID_STORE
  LEFT JOIN T_MATERIAL tm ON tm.ID_MATERIAL = ts1.ID_MATERIAL
  ORDER BY ts1.VOLUME DESC; 

/*задание 41*/
SELECT tm.NAME AS "material", tc.NAME AS "caterer", SUM(ts.VOLUME) AS "volume"
  FROM T_CATERER tc JOIN T_SUPPLY ts ON tc.ID_CATERER = ts.ID_CATERER
  JOIN T_MATERIAL tm ON tm.ID_MATERIAL = ts.ID_MATERIAL
  WHERE ts.SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY tm.NAME, tc.NAME
  ORDER BY tc.NAME, tm.NAME;

/*задание 42*/
SELECT tm.NAME AS "material", AVG(ts.VOLUME * ti.PRICE) AS "sr"
  FROM T_MATERIAL tm LEFT JOIN T_SUPPLY ts ON tm.ID_MATERIAL = ts.ID_MATERIAL
  LEFT JOIN T_INPRICE ti ON tm.ID_MATERIAL = ti.ID_MATERIAL
  WHERE ts.SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY tm.NAME
  ORDER BY tm.NAME;

/*задание 43*/
SELECT tm.NAME AS "material", SUM(ts.VOLUME) AS "summa"
  FROM T_MATERIAL tm LEFT JOIN T_SUPPLY ts ON tmL.ID_MATERIAL = ts.ID_MATERIAL
  WHERE ts.SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY tm.NAME
  ORDER BY tm.NAME;

/*задание 45*/
SELECT NAME FROM T_STORE ts INNER JOIN T_SURPLUS ts1
  ON ts.ID_STORE = ts1.ID_STORE
  GROUP BY NAME HAVING SUM(VOLUME) = 0;

/*задание 46*/
SELECT NAME FROM T_CATERER tc INNER JOIN T_SUPPLY ts
  ON tc.ID_CATERER = ts.ID_CATERER
  WHERE SUPPLY_DATE BETWEEN '01.01.2017' AND  SYSDATE
  GROUP BY NAME HAVING SUM(VOLUME) < 1000;

/*задание 47*/
SELECT NAME FROM T_CATERER tc JOIN T_SUPPLY ts
  ON tc.ID_CATERER = ts.ID_CATERER
  WHERE SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY NAME HAVING SUM(VOLUME) = MAX(VOLUME);